### ISSUE TITLE
Media queries conversion error

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/lightningcss#228]
## Input

```css
@media ( width > 0) {
    body {
        color: green;
    }
}

@media ( width < 1001px) and ( width > 999px) {
    body {
        color: green;
    }
}
```

# Output

```css
@media (min-width: .001) { /* Missing unit */
  body {
    color: green;
  }
}

@media (max-width: 1001px) /* Expected: 1000.999px */ and (min-width: 999.001px) {
  body {
    color: green;
  }
}
```

## [Demo](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A1966080%7D%2C%22source%22%3A%22%40media%20(%20width%20%3E%200)%20%7B%5Cn%20%20%20%20body%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20green%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(%20width%20%3C%201001px)%20and%20(%20width%20%3E%20999px)%20%7B%5Cn%20%20%20%20body%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20green%3B%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(%20width%20%3C%20100px)%20%7B%5Cn%20%20%20%20body%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20green%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by LeoniePhiline** [comment]
Regarding `(max-width: 1001px) /* Expected: 1000.999px */`:

The rounding is done by [dtoa_short](https://docs.rs/dtoa-short/latest/dtoa_short/index.html) when writing the `f32`.

It applies a [hard-coded precision of 6](https://github.com/upsuper/dtoa-short/blob/master/src/lib.rs#L43) and then restricts the formatted number written to the buffer by [rounding it to the given precision](https://github.com/upsuper/dtoa-short/blob/master/src/lib.rs#L126).

With an input float of `1000.99902`, `dtoa_short` first writes `01000.999` to the buffer, then shortens to 6 characters, excluding the leading `0`, : `01000.99`. The last `9` is used to start rounding up the decimals, resulting in `01001.00`, which is cleaned to `1001`.

We could:
- adjust lengths by `0.01` and `-0.01` instead of `0.001` and `-0.001`. (= lower precision to fit `dtoa_short`'s algorithm)
- or use a different floating point formatter which uses a higher precision
- or use `f64` instead of `f32`

**Comment by devongovett** [comment]
The unitless zero issue should be fixed by a84fbdbf84cd7359ce4dcc5c6f965cff9a5f8dee, which now parses the media query value according to the spec defined type. This means it'll parse as a `<length>` rather than `<number>` and the addition results in pixels. Added a test in 3ead95f.

**Comment by LeoniePhiline** [comment]
LGTM! 

[The solution](https://github.com/parcel-bundler/lightningcss/blob/a84fbdbf84cd7359ce4dcc5c6f965cff9a5f8dee/src/media_query.rs#L1072-L1156) is certainly verbose, but adding a mapping appears to be the only option. 

It might make sense to split this issue into two:
1. unitless almost-zero in media queries
2. mistaken rounding of floating point values >= 1000

Thank you very much for your continued work at parcel! It is my default and favorite bundler.

**Comment by devongovett** [comment]
Yeah I needed to ensure we parse using the correct types for some other things too, so fixing this was a nice side effect. 👍

**Comment by Anoesj** [comment]
Semi-related question, sorry if this is not the right place. Why are media queries like `@media (width < 600px) {...}` rewritten to `@media (width <= 599.999px) {...}`? Do some browsers support `<=` but not `<`?

**Comment by devongovett** [comment]
I'm not seeing that in the [playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(width%20%3C%20600px)%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D). It happens when compiling to the old `max-width` syntax though ([example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6291456%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(width%20%3C%20600px)%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)).

**Comment by mdmoreau** [comment]
@devongovett is adding/subtracting 0.001px sufficient for all browsers? Running into rounding errors after switching from PostCSS. It seems to be enough for Firefox, but in Chrome ```calc(1024px - 0.001px)``` is still registering as 1024px.

For comparison it looks like the PostCSS plugin is subtracting 0.02px or 0.001em depending on the unit used (link below). That matches the minimum values I had to use for things to work in Chrome as well. Appreciate any insight you could provide. Thanks!

https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTQwbWVkaWElMjAod2lkdGglMjAlM0MlMjAxMDI0cHgpJTIwJTdCJTVDbiUyMCUyMGNvbG9yJTNBJTIwcmVkJTNCJTVDbiU3RCU1Q24lNUNuJTQwbWVkaWElMjAod2lkdGglMjAlM0MlMjA2NGVtKSUyMCU3QiU1Q24lMjAlMjBjb2xvciUzQSUyMHJlZCUzQiU1Q24lN0QlMjIlMkMlMjJjb25maWclMjIlM0ElN0IlMjJicm93c2VycyUyMiUzQSU1QiUyMiUzRSUyMDAuMiUyNSUyMGFuZCUyMG5vdCUyMGRlYWQlMjIlNUQlMkMlMjJtaW5pbXVtVmVuZG9ySW1wbGVtZW50YXRpb25zJTIyJTNBMCUyQyUyMnN0YWdlJTIyJTNBMiUyQyUyMmxvZ2ljYWwlMjIlM0ElN0IlMjJpbmxpbmVEaXJlY3Rpb24lMjIlM0ElMjJsZWZ0LXRvLXJpZ2h0JTIyJTJDJTIyYmxvY2tEaXJlY3Rpb24lMjIlM0ElMjJ0b3AtdG8tYm90dG9tJTIyJTdEJTJDJTIyZmVhdHVyZXMlMjIlM0ElN0IlMjJuZXN0aW5nLXJ1bGVzJTIyJTNBJTVCJTIyYXV0byUyMiUyQyU3QiUyMmVkaXRpb24lMjIlM0ElMjIyMDI0LTAyJTIyJTdEJTVEJTdEJTdEJTdE

**Comment by pepelsbey** [comment]
I stumbled upon a similar issue that’s still present in v1.28.1, and it’s currently [breaking my website](https://pepelsbey.dev/) at viewport 1024px 😐

Unfortunately, `(width < 1024px)` and `(width >= 1024px)` are compiled as `(max-width: 1024px)` and `(min-width: 1024px)`, which makes them non-exclusive, e.g. they are both true at viewport 1024px. This only happens when the width is 1001px or more. It works fine for 1000px or less.

## Input

```css
@media (width < 1000px) {
  body {
    background-color: green;
  }
}

@media (width < 1001px) {
  body {
    background-color: blue;
  }
}
```

## Output

```css
@media (max-width: 999.999px) {
  body {
    background-color: green;
  }
}

@media (max-width: 1001px) {
  body {
    background-color: #00f;
  }
}
```

[Here’s the demo in the playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(width%20%3C%201000px)%20%7B%5Cn%20%20body%20%7B%5Cn%20%20%20%20background-color%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%40media%20(width%20%3C%201001px)%20%7B%5Cn%20%20body%20%7B%5Cn%20%20%20%20background-color%3A%20blue%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%221.28.1%22%7D)

/cc @devongovett

**Comment by pepelsbey** [comment]
> I'm not seeing that in the [playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(width%20%3C%20600px)%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D). It happens when compiling to the old `max-width` syntax though ([example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6291456%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(width%20%3C%20600px)%20%7B%5Cn%20%20.foo%20%7B%5Cn%20%20%20%20color%3A%20red%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)).

Try using 1001px 🥲

**Comment by LeoniePhiline** [comment]
The workaround using `f64` as described in https://github.com/parcel-bundler/lightningcss/issues/228#issuecomment-1305003408 should still be an option.

Otherwise, `dtoa_short` must be replaced.

**Comment by upsuper** [comment]
I see no problem making `write_with_prec` public, so feel free to submit a PR for that if you need.

That being said, I do have a feeling that in this case building your own algorithm that
> the number of decimals is fixed

might be a better path forward.

IIRC `dtoa-short` was built mostly to be web-compatible, or more specifically, to be compatible with what Firefox was doing with its old CSS code. But it seems that the requirements here may be slightly different, and it may deserve different solution.

Also I guess switching to `f64` may be enough for what you are trying to solve here without having to do too much.

(I noticed that Firefox just uses `f32` for the number here, so `1000.999` would be reserialized as `1001` in Firefox.)

**Comment by LeoniePhiline** [comment]
@upsuper Thank you very much for your input!

**Comment by devongovett** [comment]
The above commit solves this by using boolean logic to compile media query range syntax instead of adding fractional pixels, avoiding the problem of floating point rounding errors entirely. The input in the original issue now compiles to:

```css
@media not (max-width: 0) {
  body {
    color: green;
  }
}

@media (not (min-width: 1001px)) and (not (max-width: 999px)) {
  body {
    color: green;
  }
}
```
