### ISSUE TITLE
Plugin guide?

### ISSUE THREAD

**Issue by melMass** [parcel-bundler/lightningcss#309]
Hi,

From the readme it seems like there is a way to hook ligthingcss in other custom processes. Is there a sample plugin or guide to base on?

I'm interested in adding it to Vite. I already made a few vite plugins.

Thanks

**Comment by devongovett** [comment]
Unfortunately, Vite has hard coded their minifier and CSS transformer to postcss so plugins cannot override them. You should open an issue on the Vite repo asking for lightningcss support.

It is possible to use both postcss and lightningcss together via this plugin, but you'll miss some of the performance benefits. This will only provide transformation support for older browsers, since it cannot replace Vite's default minifier. https://github.com/lawrencecchen/vite-plugin-lightningcss

**Comment by melMass** [comment]
My bad I'm seing this just now!
Thanks I'll post the issue upstream. 
Isn't there a way to hook to Vite's postcss ?
