### ISSUE TITLE
Do not tokenise unparsed values, or offer a way to parse tokens

### ISSUE THREAD

**Issue by paulrouget** [parcel-bundler/lightningcss#321]
The result of a parsing `--foo: 10px` is a `CustomProperty` with tokenised value. If we want to compute the value of `height: var(--foo)`, we can not re-use the tokens from `CustomProperty` as there is no way to "parse" them. We have transform the tokens into a string (via `to_css`) and use `Property::parse_string("height", custom_prop.to_css(), …)`.

Does that make sense?

I would suggest either keep unparsed values as a str, or offer a `Property::parse_tokens` method (which would be better, but maybe a bit hard to do).

**Comment by devongovett** [comment]
The primary purpose of lightningcss is to minify CSS, so we have to tokenize custom properties at some point in order to safely remove whitespace and such. If you want to do variable substitution, and parse to an actual value, you'd need to replace the `var` tokens anyway. I could see supporting a method to do that, but I'd have to think more about how best to implement it.

**Comment by devongovett** [comment]
Experimented with this in https://github.com/parcel-bundler/lightningcss/commit/30139fdd08a255ebb9337993fa8e5854693261ad but ran into an issue. We'd need to store the printed css somewhere, because the lifetime of the parsed property depends on it. Ideally we'd re-use the existing tokens, but `cssparser` doesn't offer a way to do that. Ran out of time for now but feel free to play with it if you want.

**Comment by devongovett** [comment]
Implemented a `substitute_variables` function in #388.
