### ISSUE TITLE
Granularity of the visitor API is excellent!

### ISSUE THREAD

**Issue by romainmenke** [parcel-bundler/lightningcss#365]
https://github.com/parcel-bundler/lightningcss/blob/1448d96aa196db63fe76f46809cd1c9ac437321a/node/test/visitor.test.mjs#L152-L172

Being able to transform tokens and component values in both at-rules, selectors, declarations values, ... with the same transform function is really awesome.

I've spend a signification part of the past few months writing a CSS tokenizer and parsing algorithms in TypeScript because nothing existed that could do this. (CSSTree is also not usable for most PostCSS plugins)

Not having to think about how to parse a value or at-rule params to tranform `env(...)` is a really nice feature.

----

_there is no issue here, GitHub just doesn't have a better way to say "nice!" without causing noise in a pull request thread. can be closed when read._

**Comment by devongovett** [comment]
Thanks! I think this detailed parsing should help plugin authors focus on what they want to do rather than parsing/serializing, which should hopefully reduce bugs (e.g. regex shortcuts) while improving performance at the same time (e.g. not running selector/value parser in each plugin separately).

The downside is that it's a huge API surface area to maintain compatibility for (the TS definitions are almost 9,000 lines!). We'll see how that goes. 😉
