### ISSUE TITLE
CLI support for piping

### ISSUE THREAD

**Issue by jfbrennan** [parcel-bundler/lightningcss#375]
The CLI does not seem to support piping. I'm trying:
```
postcss ./src/all.css | lightningcss --minify -o ./dist/min.css
```
and I get 
```
error: The following required arguments were not provided:
    <INPUT_FILE>
```
Being able to pipe output from one tool into Lightning CSS for minification would be greatly appreciated (or tell me what I'm doing wrong 🤗). 

And yes I understand Lightning CSS wants to be my PostCSS too, but I refuse to mix tools like that. Never works correctly. Decoupled single-purpose tools are a must imo.

**Comment by devongovett** [comment]
Seems like a good feature to me!

**Comment by oylenshpeegul** [comment]
Since `std::io::read_to_string` was stabilized in Rust 1.65, getting the _contents_ could be as simple as changing

```rust
  let source = fs::read_to_string(&cli_args.input_file)?;
```
to

```rust
  let source = match &cli_args.input_file {
    Some(f) => fs::read_to_string(f)?,
    None => io::read_to_string(io::stdin())?,
  };
```
if the `channel` were bumped up in `rust-toolchain.toml`.

However, `cli_args.input_file` appears in a couple of other places, so we can't just change it to an `Option` without deciding what to use for a name in those cases when it is `None`. It looks like `options.filename` is only used to write error messages, so perhaps substituting something like "STDIN" would be appropriate there. I'm not sure what do do about

```rust
      bundler.bundle(Path::new(&cli_args.input_file)).unwrap()
```

Would substituting a fake name that is not a path on the filesystem be appropriate here?

**Comment by devongovett** [comment]
Yeah a fake name should be fine. The filename is used in error messages and source maps.
