### ISSUE TITLE
How to properly pass string to `StyleSheet::parse()`?

### ISSUE THREAD

**Issue by asartalo** [parcel-bundler/lightningcss#437]
I'm very sorry for this question. I'm very new to Rust and after a lot of searching around, I thought this is the proper place for this question. Feel free to close this issue if it does not belong here.

I have a CSS file that is loaded from an HTTP request and try to parse it. This is the code right now:

```rust
    let css_response = minreq::get(path).send()?;
    let css_str = css_response.as_str()?;
    let stylesheet = StyleSheet::parse(css_str, ParserOptions::default())?;
```

However that leads to the following error:

```
error[E0515]: cannot return value referencing local variable `css_response`
  --> src/main.rs:26:22
   |
25 |     let css_str = css_response.as_str()?;
   |                   --------------------- `css_response` is borrowed here
26 |     let stylesheet = StyleSheet::parse(css_str, ParserOptions::default())?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returns a value referencing data owned by the current function
```

What is the a correct way to do this? Right now I'm resorting to `StyleSheet::parse(...).unwrap()` and that works for me at the moment but I feel is not the correct way. I've also searched around github for demonstrations on how `StyleSheet::parse()` is used in the wild but the examples I see pass `&str` as a literal as in:

```rust
    let stylesheet = StyleSheet::parse(".foo { display: none }", ParserOptions::default())?;
```

For a more minimal reproducible code to demonstrate my problem, I think this is the closest:

```rust
    let css_str = ".foo { display: none }".to_owned();
    let stylesheet = StyleSheet::parse(&css_str, ParserOptions::default())?;
```

**Comment by devongovett** [comment]
`StyleSheet` borrows its input string, and returns parsed values that contain references to that string (e.g. URLs, string literals, etc). It doesn't copy any substrings of the input, they are just pointers into it. That means the input string must be kept around in memory for as long as the `StyleSheet` value is needed, which the Rust compiler is enforcing here. If you have a function that parses a `StyleSheet` from an owned `String` value, you cannot return the `StyleSheet` because the original string data would be dropped when it goes out of scope, and any references within the `StyleSheet` would become invalid.

The ideal way to solve this is to keep the string data around for as long as you need the stylesheet. For example, rather than returning a `StyleSheet` from the same function that loads the data, you could load the data and then do your processing while the string is still in memory and return the result of that processing. If you need to store a stylesheet for longer than a function call, you could also store the string data in a data structure like a hashmap. The [elsa](https://github.com/manishearth/elsa) crate provides append only data structures that make this safe.
