### ISSUE TITLE
minify: Drop duplicate rules

### ISSUE THREAD

**Issue by aleclarson** [parcel-bundler/lightningcss#456]
[Playground link](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.green%20%7B%5Cn%20%20background%3A%20green%3B%5Cn%7D%5Cn.red%20%7B%5Cn%20%20background%3A%20red%3B%5Cn%7D%5Cn.green%20%7B%5Cn%20%20background%3A%20green%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
.green {
  background: green;
}
.red {
  background: red;
}
.green {
  background: green;
}
```

I would expect the first `.green` rule to be dropped when minifying.

**Use case**

Using the UnoCSS library, I'm generating single-property rules based on usage in JavaScript. This happens on a per-module basis, so in production builds, I would like LightningCSS to deduplicate any rules that are used by multiple modules within a single bundle chunk.

**Comment by devongovett** [comment]
Merging non-adjacent rules is not generally safe because they have the same specificity so the order is important. For example:

```html
<p class="green red">text</p>
```

In the original code the text would be green, but if we merged the selectors it would be red.

See also #225

**Comment by devongovett** [comment]
Ah I see. Yeah for exact duplicates it could work. If either the selectors or declarations are different then it isn't safe.

**Comment by devongovett** [comment]
Implemented in the above commit. Rules are considered duplicates if they have exactly the same selectors, and the list of properties is the same. The rules may have different values for the same properties, however. 

This took a bit of work to make performant. In the general case, duplicate rules are rare, so I wanted to make sure there wasn't a big performance penalty if you didn't have any duplicates. At the moment, if there are nested rules within a style rule, it cannot be deduplicated because comparing the whole tree of rules would be expensive. Hopefully this should be rare. The performance difference when minifying bootstrap with the current implementation is about 0.2ms.
