### ISSUE TITLE
[question] why do you need napi-wasm?

### ISSUE THREAD

**Issue by jimmywarting** [parcel-bundler/lightningcss#502]
i just see that you have a dependency on `napi-wasm`, i'm just wondering why...
is it really necessary? i want to try out and use lightningcss in browser but don't see the point in why it needs to ship something NodeJS specific such as NodeJS napi to browsers or why it depend on it?

**Comment by devongovett** [comment]
In order to interface between a WASM module written in Rust and a JavaScript API, there needs to be a bridge to serialize and deserialize arguments like buffers, strings, etc. between the two worlds. In Rust, you can use something like [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) to generate this. However, we also need a similar bridge to interface between native Rust modules and Node.js (via NAPI). The idea with `napi-wasm` is to share the implementation. It allows us to reuse the NAPI module in WASM and avoid maintaining a separate one. wasm-bindgen generates very similar code anyway, so it should be roughly equivalent under the hood.
