### ISSUE TITLE
Where to get help

### ISSUE THREAD

**Issue by paulm17** [parcel-bundler/lightningcss#619]
Hey all.  I've been struggling for a week to get what should be simple things to work.  

What's the best place to get help?  I have a number of questions, the documentation isn't immediately clear on how to proceed.

Is there a lightningCSS discord?  The parcel one doesn't seem to be the right place, questions are often ignored.

Many thanks!

**Comment by devongovett** [comment]
You're welcome to ask questions here on GitHub (either in issues or discussions). At the moment, the project is mostly maintained by me, and I have limited time so I can't always guarantee that I'll be able to answer right away, but I'll try my best. The Parcel discord is also worth a shot in case someone else there knows the answer right away, but GitHub discussions are nice because they are searchable too.

**Comment by paulm17** [comment]
Thanks for taking the time to respond to this issue.  Really appreciate it!  🚀 

It's awesome that you opened up the discussions tab, as it wasn't available before the creation of this ticket.  So since I don't have any [bug] reports to file, but rather advice.  I'll close this issue and ask my questions there! 😄 

Again, thanks!
