### ISSUE TITLE
transcribes OKLCH poorly

### ISSUE THREAD

**Issue by tomByrer** [parcel-bundler/lightningcss#730]
For some reason the playground translates OKLCH into LAB, which is undesired.
I believe it is best to keep input OKLCH colors, when the only difference between [OKLCH](https://caniuse.com/?search=oklch) & [LAB]() is Safari 15.0-15.3 & Opera 97 AFAIK.

The hex colors are fine, though might be redundant in the browser compatible I selected?  If the point of hex colors is to prevent from entering P3/REC2000 color spaces, then the OKLCH/LAB CSS should be inside a P3/REC2000 `@supports` selector.

Seems CIELAB is a step back from OKLCH:
https://bottosson.github.io/posts/oklab/
https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl#oklch-vs-lch

[demo](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7929856%2C%22firefox%22%3A7995392%2C%22safari%22%3A1048576%2C%22samsung%22%3A1441792%7D%2C%22include%22%3A786431%2C%22exclude%22%3A0%2C%22source%22%3A%22%3Aroot%7B%5Cn--gray%3A%20oklch(99.9%25%200.01%2075)%3B%5Cn--red%3A%20oklch(99.9%25%200.06%2013.8)%3B%5Cn--asparagus%3A%20oklch(99.9%25%200.06%20105.6)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by devongovett** [comment]
That's because you've forced the `Colors` feature to on, which overrides the browser compatibility data we use by default. With default settings, this does not occur. [Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A7929856%2C%22firefox%22%3A7995392%2C%22safari%22%3A1048576%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%3Aroot%7B%5Cn--gray%3A%20oklch(99.9%25%200.01%2075)%3B%5Cn--red%3A%20oklch(99.9%25%200.06%2013.8)%3B%5Cn--asparagus%3A%20oklch(99.9%25%200.06%20105.6)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
